name: ev-market
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
  - jupyter
  - ipykernel
  - pyarrow
  - pip
  - pip:
      - tqdm